/* Description: Readding the Primary Keys & Foreign Keys after removing them to return the DB to its original state. */

/* Add all Primary Keys */
ALTER TABLE CAO346.AUTHORS
ADD CONSTRAINT A_PK
	PRIMARY KEY(AUTHOR);

ALTER TABLE CAO346.BINDING_TYPES
ADD CONSTRAINT BIT_PK
	PRIMARY KEY(BINDING_TYPE);

ALTER TABLE CAO346.BOOK_BINDING_TYPES
ADD CONSTRAINT BBT_PK
	PRIMARY KEY(TITLE,AUTHOR,EDITION,BINDING_TYPE);

ALTER TABLE CAO346.BOOK_CONDITION
ADD CONSTRAINT BC_PK
	PRIMARY KEY(TITLE,AUTHOR,EDITION,JACKET_CONDITION);

ALTER TABLE CAO346.BOOK_EDITIONS
ADD CONSTRAINT E_PK
	PRIMARY KEY(AUTHOR,TITLE,EDITION);
	
ALTER TABLE CAO346.BOOK_GRADE
ADD CONSTRAINT BG_PK
	PRIMARY KEY(TITLE,AUTHOR,EDITION,BOOK_GRADE);

ALTER TABLE CAO346.BOOK_TYPE
ADD CONSTRAINT BT_PK
	PRIMARY KEY(TITLE,AUTHOR,EDITION,BOOK_TYPE);

ALTER TABLE CAO346.GRADE
ADD CONSTRAINT G_PK
	PRIMARY KEY(BOOK_GRADE);

ALTER TABLE CAO346.JACKET_CONDITION
ADD CONSTRAINT JC_PK
	PRIMARY KEY(JACKET_CONDITION);

ALTER TABLE CAO346.PUBLISHERS
ADD CONSTRAINT P_PK
	PRIMARY KEY(PUBLISHER);
	
ALTER TABLE CAO346.PUBLISHER_BOOKS
ADD CONSTRAINT PB_PK
	PRIMARY KEY(TITLE,AUTHOR,EDITION,PUBLISHER);

ALTER TABLE CAO346.TYPES
ADD CONSTRAINT T_PK
	PRIMARY KEY(BOOK_TYPE);


/* Add all Foreign Keys */
ALTER TABLE CAO346.BOOK_BINDING_TYPES
ADD CONSTRAINT BBT_TO_BE_FK
	FOREIGN KEY (E_PK) REFERENCES 
	CAO346.BOOK_EDITIONS(E_PK);
	
ALTER TABLE CAO346.BOOK_BINDING_TYPES
ADD CONSTRAINT BBT_TO_BT_FK0
	FOREIGN KEY (BIT_PK) REFERENCES 
	CAO346.BINDING_TYPES(BIT_PK);
	
ALTER TABLE CAO346.BOOK_CONDITION
ADD CONSTRAINT BC_TO_BE_FK
	FOREIGN KEY (E_PK) REFERENCES 
	CAO346.BOOK_EDITIONS(E_PK);
	
ALTER TABLE CAO346.BOOK_CONDITION
ADD CONSTRAINT BC_TO_JC_FK
	FOREIGN KEY (JC_PK) REFERENCES 
	CAO346.JACKET_CONDITION(JC_PK);

ALTER TABLE CAO346.BOOK_EDITIONS
ADD CONSTRAINT BE_TO_A
	FOREIGN KEY (A_PK) REFERENCES 
	CAO346.AUTHORS(A_PK);

ALTER TABLE CAO346.BOOK_GRADE
ADD CONSTRAINT BG_TO_BE_FK
	FOREIGN KEY (E_PK) REFERENCES 
	CAO346.BOOK_EDITIONS(E_PK);

ALTER TABLE CAO346.BOOK_GRADE
ADD CONSTRAINT BG_TO_G_FK
	FOREIGN KEY (G_PK) REFERENCES 
	CAO346.GRADE(G_PK);

ALTER TABLE CAO346.BOOK_TYPE
ADD CONSTRAINT BT_TO_BE_FK
	FOREIGN KEY (E_PK) REFERENCES 
	CAO346.BOOK_EDITIONS(E_PK);

ALTER TABLE CAO346.BOOK_TYPE
ADD CONSTRAINT BT_TO_T_FK
	FOREIGN KEY (T_PK) REFERENCES 
	CAO346.TYPES(T_PK);

ALTER TABLE CAO346.PUBLISHER_BOOKS
ADD CONSTRAINT PB_TO_BE_FK
	FOREIGN KEY (E_PK) REFERENCES 
	CAO346.BOOK_EDITIONS(E_PK);

ALTER TABLE CAO346.PUBLISHER_BOOKS
ADD CONSTRAINT PB_TO_P_FK
	FOREIGN KEY (P_PK) REFERENCES 
	CAO346.PUBLISHERS(P_PK);

