/* Description: As primary keys are indexes into our tables, we are temporarily undoing our optimization by dropping primary keys and foreign keys from our DB and testing the run-time without them. */

/* Drop all Foreign Keys */
ALTER TABLE CAO346.BOOK_BINDING_TYPES
DROP CONSTRAINT BBT_TO_BE_FK;

ALTER TABLE CAO346.BOOK_BINDING_TYPES
DROP CONSTRAINT BBT_TO_BT_FK;

ALTER TABLE CAO346.BOOK_CONDITION
DROP CONSTRAINT BC_TO_BE_FK;

ALTER TABLE CAO346.BOOK_CONDITION
DROP CONSTRAINT BC_TO_JC_FK;

ALTER TABLE CAO346.BOOK_EDITIONS
DROP CONSTRAINT BE_TO_A;

ALTER TABLE CAO346.BOOK_GRADE
DROP CONSTRAINT BG_TO_BE_FK;

ALTER TABLE CAO346.BOOK_GRADE
DROP CONSTRAINT BG_TO_G_FK;

ALTER TABLE CAO346.BOOK_TYPE
DROP CONSTRAINT BT_TO_BE_FK;

ALTER TABLE CAO346.BOOK_TYPE
DROP CONSTRAINT BT_TO_T_FK;

ALTER TABLE CAO346.PUBLISHER_BOOKS
DROP CONSTRAINT PB_TO_BE_FK;

ALTER TABLE CAO346.PUBLISHER_BOOKS
DROP CONSTRAINT PB_TO_P_FK;


/* Drop all Primary Keys */
ALTER TABLE CAO346.AUTHORS
DROP CONSTRAINT A_PK;

ALTER TABLE CAO346.BINDING_TYPES
DROP CONSTRAINT BIT_PK;

ALTER TABLE CAO346.BOOK_BINDING_TYPES
DROP CONSTRAINT BBT_PK;

ALTER TABLE CAO346.BOOK_CONDITION
DROP CONSTRAINT BC_PK;

ALTER TABLE CAO346.BOOK_EDITIONS
DROP CONSTRAINT E_PK;

ALTER TABLE CAO346.BOOK_GRADE
DROP CONSTRAINT BG_PK;

ALTER TABLE CAO346.BOOK_TYPE
DROP CONSTRAINT BT_PK;

ALTER TABLE CAO346.GRADE
DROP CONSTRAINT G_PK;

ALTER TABLE CAO346.JACKET_CONDITION
DROP CONSTRAINT JC_PK;

ALTER TABLE CAO346.PUBLISHERS
DROP CONSTRAINT P_PK;

ALTER TABLE CAO346.PUBLISHER_BOOKS
DROP CONSTRAINT PB_PK;

ALTER TABLE CAO346.TYPES
DROP CONSTRAINT T_PK;
