-- Create tables
CREATE TABLE GCWZF4.BOOK_EDITIONS (
	BID NUMBER(8),
	TITLE VARCHAR2(200),
	EDITION VARCHAR2(60),
	ISBN VARCHAR2(13),
	PAGES VARCHAR2(9),
	PUBLISH_YEAR VARCHAR2(4),
	NOTES VARCHAR2(900)		
);

CREATE TABLE GCWZF4.PUBLISHER_BOOKS (
	BID NUMBER(8),	
	PUBLISHER VARCHAR2(80)
);

CREATE TABLE GCWZF4.BOOK_CONDITION (
	BID NUMBER(8),
	JACKET_CONDITION VARCHAR2(60)
);

CREATE TABLE GCWZF4.BOOK_BINDING_TYPES (
	BID NUMBER(8),
	BINDING_TYPE VARCHAR2(40)
);

CREATE TABLE GCWZF4.AUTHOR_BOOKS (
	BID NUMBER(8),
	AUTHOR VARCHAR2(100)
);

CREATE TABLE GCWZF4.PUBLISHERS (
	PUBLISHER VARCHAR2(100)
);

CREATE TABLE GCWZF4.AUTHORS (
	AUTHOR VARCHAR2(100)
);

CREATE TABLE GCWZF4.JACKET_CONDITIONS (
	JACKET_CONDITION VARCHAR2(60)
);

CREATE TABLE GCWZF4.BINDING_TYPES (
	BINDING_TYPE VARCHAR2(40)
);

CREATE TABLE GCWZF4.BOOK_GRADE (
	BID NUMBER(8),
	BOOK_GRADE VARCHAR2(40)
);

CREATE TABLE GCWZF4.BOOK_TYPE (
	BID NUMBER(8),
	BOOK_TYPE VARCHAR2(50)
);

CREATE TABLE GCWZF4.GRADE (
	BOOK_GRADE VARCHAR2(40)
);

CREATE TABLE GCWZF4.TYPES (
	BOOK_TYPE VARCHAR2(50)
);

-- Create primary keys

ALTER TABLE GCWZF4.BOOK_EDITIONS
ADD CONSTRAINT editions_pk
	PRIMARY KEY (BID, TITLE, EDITION);

ALTER TABLE GCWZF4.PUBLISHER_BOOKS
ADD CONSTRAINT pb_pk
	PRIMARY KEY (PUBLISHER, BID);

ALTER TABLE GCWZF4.BOOK_CONDITION
ADD CONSTRAINT bc_pk
	PRIMARY KEY (BID, JACKET_CONDITION);

ALTER TABLE GCWZF4.BOOK_BINDING_TYPES
ADD CONSTRAINT bbt_pk
	PRIMARY KEY (BID, BINDING_TYPE);

ALTER TABLE GCWZF4.AUTHOR_BOOKS
ADD CONSTRAINT ab_pk
	PRIMARY KEY (AUTHOR, BID);

ALTER TABLE GCWZF4.BOOK_GRADE
ADD CONSTRAINT bg_pk
	PRIMARY KEY (BID, BOOK_GRADE);

ALTER TABLE GCWZF4.BOOK_TYPE
ADD CONSTRAINT bt_pk	
	PRIMARY KEY (BID, BOOK_TYPE);

ALTER TABLE GCWZF4.AUTHORS
ADD CONSTRAINT a_pk
	PRIMARY KEY (AUTHOR);

ALTER TABLE GCWZF4.PUBLISHERS
ADD CONSTRAINT p_pk
	PRIMARY KEY (PUBLISHER);

ALTER TABLE GCWZF4.JACKET_CONDITIONS
ADD CONSTRAINT jc_pk
	PRIMARY KEY (JACKET_CONDITION);

ALTER TABLE GCWZF4.BINDING_TYPES
ADD CONSTRAINT bit_pk
	PRIMARY KEY (BINDING_TYPE);

ALTER TABLE GCWZF4.GRADE
ADD CONSTRAINT g_pk
	PRIMARY KEY (BOOK_GRADE);

ALTER TABLE GCWZF4.TYPES
ADD CONSTRAINT t_pk
	PRIMARY KEY (BOOK_TYPE);

-- Create foreign keys

ALTER TABLE GCWZF4.PUBLISHER_BOOKS
ADD CONSTRAINT pb_fk
	FOREIGN KEY (PUBLISHER) REFERENCES GCWZF4.PUBLISHERS(PUBLISHER);

ALTER TABLE GCWZF4.BOOK_CONDITION
ADD CONSTRAINT bc_fk
	FOREIGN KEY (JACKET_CONDITION) REFERENCES GCWZF4.JACKET_CONDITIONS(JACKET_CONDITION);

ALTER TABLE GCWZF4.BOOK_BINDING_TYPES
ADD CONSTRAINT bbt_fk
	FOREIGN KEY (BINDING_TYPE) REFERENCES GCWZF4.BINDING_TYPES(BINDING_TYPE);

ALTER TABLE GCWZF4.BOOK_GRADE
ADD CONSTRAINT bg_fk
	FOREIGN KEY (BOOK_GRADE) REFERENCES GCWZF4.GRADE(BOOK_GRADE);

ALTER TABLE GCWZF4.BOOK_TYPE
ADD CONSTRAINT bt_fk
	FOREIGN KEY (BOOK_TYPE) REFERENCES GCWZF4.TYPES(BOOK_TYPE);

ALTER TABLE GCWZF4.AUTHOR_BOOKS
ADD CONSTRAINT ab_fk
	FOREIGN KEY (AUTHOR) REFERENCES GCWZF4.AUTHORS(AUTHOR);

-- Create sequence for BID

DROP SEQUENCE GCWZF4.BOOK_SEQ;

CREATE SEQUENCE GCWZF4.BOOK_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

DROP TRIGGER AUTO_INCREMENT_BOOK_INSERT;

CREATE OR REPLACE TRIGGER  auto_increment_book_insert
BEFORE INSERT ON GCWZF4.BOOK_EDITIONS
FOR EACH ROW
BEGIN
	SELECT cao346.BOOK_SEQ.nextval
	INTO :NEW.BID
	FROM DUAL;
END;

-- Testing auto increment before insert

DELETE FROM GCWZF4.BOOK_EDITIONS
WHERE BID = '3';

INSERT INTO GCWZF4.BOOK_EDITIONS (TITLE, EDITION, ISBN, PAGES, PUBLISH_YEAR, NOTES)
VALUES ('title', 'edition', '1234567891123', '5', '1111', 'notes' );

INSERT INTO GCWZF4.BOOK_EDITIONS (TITLE, EDITION, ISBN, PAGES, PUBLISH_YEAR, NOTES)
VALUES ('titlee', 'ed', '5697854692315', '2', '1547', 'notes');

INSERT INTO GCWZF4.BOOK_EDITIONS (TITLE, EDITION, ISBN, PAGES, PUBLISH_YEAR, NOTES)
VALUES ('titleee', 'edd', '5697854692315', '2', '1547', 'notes');

SELECT *
FROM GCWZF4.BOOK_EDITIONS;

-- Grant privileges to George

GRANT ALL PRIVILEGES
ON GCWZF4.AUTHORS TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.AUTHOR_BOOKS TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.BINDING_TYPES TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.BOOK_BINDING_TYPES TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.BOOK_CONDITION TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.BOOK_EDITIONS TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.BOOK_GRADE TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.BOOK_TYPE TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.GRADE TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.JACKET_CONDITIONS TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.PUBLISHERS TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.PUBLISHER_BOOKS TO GCWZF4;

GRANT ALL PRIVILEGES
ON GCWZF4.TYPES TO GCWZF4;
