--- example for the following request
--- http://localhost:5000/add_book?title=a&img_path=c&edition=0&gutenberg_path=d&publisher=e&notes=f&isbn=g&publish_year=h&pages=i&binding_type=j&jacket_condition=k&author=b

INSERT INTO GCWZF4.AUTHORS(AUTHOR,IMAGE_PATH) 
VALUES ('b','c');
INSERT INTO GCWZF4.BOOK_EDITIONS(TITLE,EDITION,AUTHOR,ISBN,PAGES,PUBLISH_YEAR,NOTES,GUTENBERG_PATH) 
VALUES ('a','0','b','g','i','h','f','d');
INSERT INTO GCWZF4.JACKET_CONDITIONS(JACKET_CONDITION) 
VALUES ('k');
INSERT INTO GCWZF4.BOOK_CONDITION(TITLE, AUTHOR, EDITION, JACKET_CONDITION) 
VALUES ('a','b','0','k');
INSERT INTO GCWZF4.PUBLISHERS(PUBLISHER) 
VALUES ('e');
INSERT INTO GCWZF4.PUBLISHER_BOOKS(TITLE, AUTHOR, EDITION, PUBLISHER) 
VALUES ('a','b','0','e');
INSERT INTO GCWZF4.BINDING_TYPES(BINDING_TYPE) 
VALUES ('j');
INSERT INTO GCWZF4.BOOK_BINDING_TYPES(TITLE, AUTHOR, EDITION, BINDING_TYPE) 
VALUES ('a','b','0','j');