EXPLAIN PLAN SET statement_id = 'decent_query' FOR
SELECT BOOK_EDITIONS.TITLE, BOOK_EDITIONS.AUTHOR, PUBLISHER_BOOKS.PUBLISHER 
FROM CAO346.BOOK_EDITIONS
JOIN CAO346.PUBLISHER_BOOKS ON BOOK_EDITIONS.TITLE = PUBLISHER_BOOKS.TITLE
JOIN CAO346.BOOK_BINDING_TYPES ON BOOK_EDITIONS.TITLE = BOOK_BINDING_TYPES.TITLE
JOIN CAO346.BOOK_CONDITION ON BOOK_EDITIONS.TITLE = BOOK_CONDITION.TITLE
JOIN CAO346.BOOK_TYPE ON BOOK_EDITIONS.TITLE = BOOK_TYPE.TITLE
WHERE BOOK_CONDITION.JACKET_CONDITION = 'Good'
AND BOOK_BINDING_TYPES.BINDING_TYPE = 'Hard Cover'
AND BOOK_TYPE = 'Mystery'
ORDER BY BOOK_EDITIONS.TITLE, BOOK_EDITIONS.AUTHOR, PUBLISHER_BOOKS.PUBLISHER;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());

EXPLAIN PLAN SET statement_id = 'bad_query' FOR
SELECT BOOK_EDITIONS.TITLE, BOOK_EDITIONS.AUTHOR, PUBLISHER_BOOKS.PUBLISHER 
FROM 
	CAO346.BOOK_EDITIONS, 
	CAO346.PUBLISHER_BOOKS, 
	CAO346.BOOK_BINDING_TYPES, 
	CAO346.BOOK_CONDITION,
	CAO346.BOOK_TYPE
WHERE
	BOOK_EDITIONS.TITLE = PUBLISHER_BOOKS.TITLE AND
	BOOK_EDITIONS.TITLE = BOOK_BINDING_TYPES.TITLE AND
	BOOK_EDITIONS.TITLE = BOOK_CONDITION.TITLE AND
	BOOK_EDITIONS.TITLE = BOOK_TYPE.TITLE AND
	BOOK_CONDITION.JACKET_CONDITION = 'Good'AND 
	BOOK_BINDING_TYPES.BINDING_TYPE = 'Hard Cover' AND
	BOOK_TYPE = 'Mystery'
ORDER BY BOOK_EDITIONS.TITLE, BOOK_EDITIONS.AUTHOR, PUBLISHER_BOOKS.PUBLISHER;;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());

SELECT BOOK_EDITIONS.TITLE, BOOK_EDITIONS.AUTHOR, PUBLISHER_BOOKS.PUBLISHER 
FROM CAO346.BOOK_EDITIONS
LEFT OUTER JOIN 
	CAO346.PUBLISHER_BOOKS 
	ON BOOK_EDITIONS.TITLE = PUBLISHER_BOOKS.TITLE
LEFT OUTER JOIN 
	CAO346.BOOK_BINDING_TYPES 
	ON BOOK_EDITIONS.TITLE = BOOK_BINDING_TYPES.TITLE
LEFT OUTER JOIN 
	CAO346.BOOK_CONDITION 
	ON BOOK_EDITIONS.TITLE = BOOK_CONDITION.TITLE
LEFT OUTER JOIN 
	CAO346.BOOK_TYPE 
	ON BOOK_EDITIONS.TITLE = BOOK_TYPE.TITLE
WHERE BOOK_CONDITION.JACKET_CONDITION = 'Good'
AND BOOK_BINDING_TYPES.BINDING_TYPE = 'Hard Cover'
AND BOOK_TYPE = 'Mystery'
ORDER BY BOOK_EDITIONS.TITLE, BOOK_EDITIONS.AUTHOR, PUBLISHER_BOOKS.PUBLISHER;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());
